package questions;

	import java.util.Random;
	import java.util.Scanner;

	class GuessingGame{
	    public int compNumber; //compNumber is the number generated by the Computer that the user has to guess
	    public int userGuess; //The number user guesses
	    public int noOfGuesses = 0; //It is the number that we count no. of times, the user takes to guess the correct number

	    public int getNoOfGuesses() {
	        return noOfGuesses;
	    }

	    public void setNoOfGuesses(int noOfGuesses) {
	        this.noOfGuesses = noOfGuesses;
	    }

	    GuessingGame(){
	        Random rand = new Random();
	        this.compNumber = rand.nextInt(100);
	    }
	    
	    void userInput(){
	        System.out.println("Please enter a number: ");
	        Scanner s = new Scanner(System.in);
	        userGuess = s.nextInt();
	    }
	    boolean correctNumber(){
	        noOfGuesses++;
	        if (userGuess==compNumber){
	            System.out.format("Congratulations! Your guessing is correct! The answer is %d\nYou guessed it in %d attempts", compNumber, noOfGuesses);
	            return true;
	        }
	        else if(userGuess<compNumber){
	            System.out.println("Oops! SORRY, Try again with a higher number.");
	        }
	        else {
	            System.out.println("Oops! SORRY, Try again with a lower number.");
	        }
	        return false;
	    }

	}
	public class NumberGuessing {
	    public static void main(String[]args) {
	        System.out.println("WELCOME TO THE NUMBER GUESSING GAME! CAN YOU GUESS THE NUMBER FROM 0 TO 100 THAT MATCHES WITH ME?? ");
	        GuessingGame game = new GuessingGame();
	        boolean rightGuess= false;
	        while(!rightGuess){
	            game.userInput();
	            rightGuess = game.correctNumber();
	        }

	    }
	}
	

